name: Deploy to Cocoapods

on:
  release:
    types: [released]

jobs:
  unit_tests:
    uses: ./.github/workflows/tests_workflow.yml

  deploy:
    runs-on: macOS-latest
    needs: unit_tests

    steps:
    - uses: szenius/set-timezone@v1.2
      with:
        timezoneMacos: "Asia/Baghdad"
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"
    - uses: actions/checkout@v4
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
