name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set Timezone to +3 (With input)
    - uses: szenius/set-timezone@v1.2
      with:
        timezoneMacos: "Asia/Baghdad"
    - name: Install Cocoapods
      run: |
        gem install cocoapods
        pod install --project-directory=Example
    - name: Run Tests
      run: |
        set -eo pipefail
        xcodebuild test -enableCodeCoverage YES -workspace Example/MuslimData.xcworkspace -scheme MuslimData-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro' | xcpretty

